version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USER=my_loveletter_user
      - DB_PASSWORD=mypass
      - DB_NAME=loveletter
    container_name: love_letter_server
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./server
      dockerfile: Dockerfile.bdd
    environment:
      MYSQL_DATABASE: loveletter
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_USER: my_loveletter_user
      MYSQL_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

