version: '3'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "3000:80"
    container_name: love_letter_server
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./server
      dockerfile: Dockerfile.bdd
    environment:
      MYSQL_DATABASE: loveletter
      MYSQL_ROOT_PASSWORD: myrootpass
      MYSQL_USER: my_loveletter_user
      MYSQL_PASSWORD: mypass
    volumes:
      - db_data:/var/lib/mysql

  integration_tests:
    build: 
      context: ./integration_test
      dockerfile: Dockerfile.integration
    container_name: love_letter_integration_tests
    depends_on:
      - server

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:

