# Utilisez une image de base avec les dépendances nécessaires pour exécuter vos tests
FROM node:14

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copiez le package.json et le package-lock.json dans le conteneur
COPY ./package*.json .

# Copiez tous les fichiers du projet dans le conteneur
COPY ./src .
COPY ./unit_test/*.js .

# Installez les dépendances de l'application pour le test, y compris Jest
RUN npm install jest --save-dev

# Exécuter les tests
CMD ["npm", "test"]
